language: generic

dist: bionic

jobs:
  include:
    - os: linux
      language: python
      python: 3.6
      compiler: gcc
      env:
        - CC=gcc-10
        - CXX=g++-10
      addons:
        apt:
          packages: ['g++-10']
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

before_install:
  - export PATH=$(printf "%s\n" "$PATH" | tr ":" "\n" | grep -vF cmake | tr "\n" ":" | sed -e "s/:$//")

install:
  - >-
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null |
    gpg --dearmor - |
    sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt-get update
  - sudo apt-get install cmake -y
  - cmake --version

script:
  - which cmake
  - printf "%s\n" "$PATH"
