name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    container:
      image: gcc:10

    name: Test

    steps:
      - uses: actions/checkout@master

      - name: CMake
        run: cmake --version
