name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    container:
      image: gcc:10
      options: -v /usr/local:/host_usr_local

    name: Test

    env:
      PATH: "${{ env.PATH }}:/host_usr_local/bin"

    steps:
      - uses: actions/checkout@master

      - name: CMake
        run: cmake --version
