name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    container:
      image: gcc:10
      options: -v /usr/local:/host_usr_local

    name: Test

    steps:
      - uses: actions/checkout@master

      - name: CMake
        run: |
          PATH="$PATH:/host_usr_local/bin"
          cmake --version
